Repository NativeScript/nativescript-geolocation, pull requests merged in 2019-05, with the labels that each got.

#215 Chore: bump bersion to 5.1.0
  src/package.json
Labels: new PR

#216 chore: update to 5.4
  .travis.yml
  demo-angular/package.json
  demo-vue/package.json
  demo/app/package.json
  demo/package.json
Labels: cla: yes, new PR

#219 chore: update to node 10, set trusty distribution
  .travis.yml
Labels: cla: yes
